config/routes.rb
Bingoapp::Application.routes.draw do
  root :to => 'home#index'

  resources :games, only: [:new, :create, :show] do
    resources :cards, :only => [:new, :show] do
      member do
        put 'clicked'
        post 'join'
      end
    end

    get 'moves', :on => :member
  end
end

app/models/card.rb
class Card
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :words, type: Array, default: []
  field :found, type: Array, default: []
  field :won, type: Boolean, default: false
  field :won_at, type: DateTime

  attr_accessible :name
  embedded_in :game

  validates :name, presence: true

  before_create :shuffle

  def shuffle
    write_attribute(:words, game.words.shuffle)
  end

  def matrix
    @matrix ||= words.in_groups_of(size)
  end

  def hashed_matrix
    matrix.map do |row|
      row.map{ |word| {word: word, hash: Digest::MD5.hexdigest(word)} }
    end
  end

  def size
    @size ||= Math.sqrt(words.size).to_i
  end

  def at(row = 0, column = 0)
    matrix[row][column]
  end

  def has?(row = 0, column = 0)
    found.include? at(row, column)
  end

  def has_word?(word)
    found.include?(word)
  end

  def found!(row = 0, column = 0)
    word = at(row, column)
    found << word unless has_word?(word)
  end

  def unfind!(row = 0, column = 0)
    word = at(row, column)
    found.delete(word) if has_word?(word)
  end

  def bingo?
    return false if found.size < size

    size.times do |i|
      return true if row(i).all?{ |word| has_word?(word) }
      return true if column(i).to_a.all?{ |word| has_word?(word) }
    end

    diagonal(0).all?{ |word| has_word?(word) } || diagonal(size - 1).all?{ |word| has_word?(word) }
  end

  def row(i)
    matrix[i]
  end

  def column(i)
    (0...size).collect{ |n| matrix[n][i] }
  end

  def diagonal(start)
    m = start.zero? ? matrix : matrix.map(&:reverse)
    (0...size).collect{ |i| m[i][i] }
  end

  def as_json(options = nil)
    {
      id: id,
      game_id: game.id,
      name: name,
      matrix: hashed_matrix
    }
  end
end

app/models/game.rb
class Game
  include Mongoid::Document
  include Mongoid::Timestamps

  MinimumWords = 9

  field :name, type: String
  field :token, type: String
  field :words, type: Array
  field :active, type: Boolean, default: true

  attr_accessible :name, :words
  embeds_many :cards

  validates :name, presence: true, length: {within: 3..150}
  validates :token, presence: true, uniqueness: true

  validate :must_have_enough_words
  before_validation :set_token

  def self.generate_token(seed = nil)
    (seed || Time.now).to_i.to_s(16)
  end

  def words=(words)
    words = Array(words.split("\n")) unless words.is_a?(Array)
    cleaned_words = words \
      .map(&:strip) \
      .map(&:downcase) \
      .map{ |word| word.gsub /[^\w]/, '' } \
      .uniq
      .reject{ |word| word.blank? }[0...MinimumWords]

    write_attribute(:words, cleaned_words)
  end

  def won?
  end

  def winner
  end

private

  def set_token
    write_attribute :token, self.class.generate_token
  end

  def must_be_perfect_square
    unless (words.size.to_i ** 0.5 == Math.sqrt(words.size))
      errors.add(:words, 'The number of words you provided wasn\'t a perfect square (We can\'t generate a proper board like that!)')
    end
  end

  def must_have_enough_words
    if words.size < MinimumWords
      errors.add(:words, 'You did\'t provide enough words! For a game we need %d words.' % MinimumWords)
    end
  end
end

app/models/move.rb
class Move
  def initialize(name, word, found = true)
    @name, @word, @found = name, word, found
    @hash = Digest::MD5.hexdigest(word)
  end

  def to_h
    {
      name: @name,
      found: @found,
      word: @word,
      hash: @hash
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  protect_from_forgery :except => :authorize
  respond_to :json, :only => [:clicked]

  def new
    game = Game.find(params[:game_id])
    card = game.cards.build(name: (session[:name] || "Player #{game.cards.size + 1}"))

    if card.save
      redirect_to game_card_path(game, card)
    else
      flash[:notice] = "Whoah. Card creation failed. Try again maybe?"
      redirect_to game_path(game)
    end
  end

  def show
    @game = Game.find(params[:game_id])
    @card = @game.cards.find(params[:id])

    render :show
  end

  def clicked
    game = Game.find params[:game_id]
    card = game.cards.find params[:id]
    row, col = params[:row], params[:col]
    found = true

    if card.has?(row, col)
      card.unfind! row, col
      found = false
    else
      card.found! row, col
    end

    move = Move.new(card.name, card.at(row, col), found)
    Pusher["presence-#{game.id}"].trigger! 'cell_clicked', move.to_h

    card.save

    respond_with card, :status => 200
  end

  def join
    game = Game.find params[:game_id]
    card = game.cards.find params[:id]

    response = Pusher[params[:channel_name]].authenticate(params[:socket_id],
    {
      :user_id => card.id,
      :user_info => {
        :name => card.name
      }
    })

    render :json => response
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  respond_to :html
  respond_to :json, :only => [:moves]

  def new
    @game = Game.new(name: 'Bingo!', words: [])
    respond_with @game
  end

  def create
    @game = Game.new params[:game]

    if @game.save
      flash.notice = 'Game Created!'
      redirect_to @game
    else
      render :new
    end
  end

  def show
    @game = Game.find params[:id]
    respond_with @game
  end

  def moves
    game = Game.find params[:id]
    moves = []

    game.cards.each do |card|
      card.found.each do |word|
        moves << Move.new(card.name, word, true).to_h
      end
    end

    respond_with moves
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
  def hash(word)
    Digest::MD5.hexdigest(word)
  end
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cards/show.html.erb
<%= content_for :head do %>
  <script src="http://js.pusher.com/1.11/pusher.min.js" type="text/javascript"></script>
  <%= javascript_tag do %>
    window.PUSHER_KEY = '<%= PusherConfig['app_key'] %>';
    window.PUSHER_DEBUG = false; //<%= PusherConfig['debug'] %>;
    window.Card = <%= @card.to_json.html_safe %>;
  <% end %>
<% end %>

<%= content_for :sidebar do %>
  <h2>
    <%= @game.name %>
    <small>(<%=link_to 'view', game_path(@game) %>)</small>
  </h2>

  <p>Started: <%= @game.created_at.strftime '%B %d' %></p>

  <div id='players'>
    <!-- rendered by PlayersView -->
  </div>
<% end %>

<div id='board'>
  <!-- rendered by BoardView -->
</div>

<div id='game_over' style='display:<%= 'none' unless @game.won? %>;'><%= "<span>Game won by #{h @game.winner}!</span>" if @game.won? %></div>

<script name='cell-template' type='text/html'>
<div class='indicator' style='display:none;'>
  <%= image_tag 'indicator.gif' %>
</div>
{{word}}
<div class='users'></div>
</script>

<script name='players-template' type='text/html'>
<h3>Players ({{count}})</h3>
<ol id='whos_playing'>
</ol>
</script>

app/views/games/new.html.erb
<div class='form'>
  <h2>Create a NEW Game!</h2>
  <p>You can create a custom Bingo! game to play with your friends!</p>
    
  <%= form_for @game do |f| %>
    <label for="game_name" class='<%= 'with_errors' unless @game.errors[:name].blank? %>'>
      Game Name<br/>
      <small>Something memorable :)</small>
    </label>
    <input type="text" name="game[name]" value="<%= @game.name %>" id="game_name">
    <div class='form_error'><%= Array(@game.errors[:name]).join("<br/>") %></div>
    <br clear='both' />
    
    <label for="game_words" class='<%= 'with_errors' unless @game.errors[:words].blank? %>'>
      Game Words<br/>
      <small>You need <%= Game::MinimumWords %> words for a game.</small>
    </label>
    <textarea name="game[words]" rows="8" class='styled'><%= @game.words.join("\n") %></textarea>
    <div class='form_error'>
      <% @game.errors[:words].each do |message, attr| %>
        <%= message %><br/>
      <% end %>
    </div>

    <input type="submit" class='submit' value="Create Game &rarr;">
    <br clear='both' />
  <% end %>
</div>

app/views/games/show.html.erb
<h1><%=h @game.name %></h1>

<div class='block'>
  <strong>Public Game URL:</strong>
  <small>Pass this URL to your friends to start playing the game.</small>
  <p><%= link_to game_url(@game) %></p>
</div>

<% if @game.won? %>
  <h3>This game has been won by <%=h @game.winner %>!</h3>
  <p>This game is over and will be automatically swept up. If you would like to start a new game, <%= link_to 'click here', new_game_path %>.</p>
<% else %>

  <div class='block'>
    <strong>Create a NEW Player Card</strong>
    <small>To start playing Bingo! you need your own card. Generate one below! If you already created a card, select it from below to start playing.</small>
    <p><%= link_to 'I need a card!', new_game_card_path(@game) %></p>
  </div>

  <% if @game.cards.empty? %>
    <h3>You don't have any active cards!</h3>
    <p>To start playing, click the "Make me a card!" link below.</p>
  <% else %>
    <h3>Current Players</h3>
    <ul>
      <% @game.cards.each do |card| %>
        <li><%= link_to h(card.name), game_card_path(@game, card) %> &ndash; <%= card.created_at.strftime '%m/%d/%Y' %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/home/index.html.erb
<%= link_to 'New Game', new_game_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bingoapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <script src="http://js.pusherapp.com/1.6/pusher.js" type="text/javascript"></script>
  <%= javascript_include_tag "application" %>
  <script type="text/javascript" charset="utf-8">
  </script>
  <%= csrf_meta_tags %>
  <%= content_for(:head) %>
</head>
<body>

  <div id='header'>
    <h1>Bingo!</h1>
  </div>
  <div id='frame'>
    <div class='content'>
      <%= render partial: 'share/flash' %>
      <%= yield %>
    </div>
  </div>
  <div id='sidebar'>
    <div class='content'>
      <%= content_for?(:sidebar) ? yield(:sidebar) : render(partial: 'share/default_sidebar') %>
    </div>
  </div>

</body>
</html>

app/views/share/_default_sidebar.html.erb
<h2>Welcome to Bingo!</h2>
<p>To get started with a new game, choose "New Game"</p>

app/views/share/_flash.html.erb
<div id='flash'>
</div>